-- MySQL Script generated by MySQL Workbench
-- Mon Jan 10 19:45:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecenario2-bazarDigital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecenario2-bazarDigital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecenario2-bazarDigital` DEFAULT CHARACTER SET utf8 ;
USE `ecenario2-bazarDigital` ;

-- -----------------------------------------------------
-- Table `ecenario2-bazarDigital`.`articles_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecenario2-bazarDigital`.`articles_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecenario2-bazarDigital`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecenario2-bazarDigital`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(9,2) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `stock` TINYINT NOT NULL,
  `use_profesional` INT NOT NULL,
  `typeId` INT NOT NULL,
  `articleCategoryId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_articles_category_idx` (`articleCategoryId` ASC) VISIBLE,
  CONSTRAINT `fk_articles_category`
    FOREIGN KEY (`articleCategoryId`)
    REFERENCES `ecenario2-bazarDigital`.`articles_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecenario2-bazarDigital`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecenario2-bazarDigital`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecenario2-bazarDigital`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecenario2-bazarDigital`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `dni` TINYINT NOT NULL,
  `salary` TINYINT NOT NULL,
  `rolId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employess_rol_idx` (`rolId` ASC) VISIBLE,
  CONSTRAINT `fk_employess_rol`
    FOREIGN KEY (`rolId`)
    REFERENCES `ecenario2-bazarDigital`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecenario2-bazarDigital`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecenario2-bazarDigital`.`sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `aricle` VARCHAR(45) NOT NULL,
  `payment_method` VARCHAR(45) NOT NULL,
  `total_amount` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecenario2-bazarDigital`.`employees_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecenario2-bazarDigital`.`employees_access` (
  `id` INT NOT NULL,
  `saleId` INT NOT NULL,
  `articlesId` INT NOT NULL,
  `rolId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employess_acces_idx` (`rolId` ASC) VISIBLE,
  INDEX `fk_employess_articles_idx` (`articlesId` ASC) VISIBLE,
  INDEX `fk_employess_sales_idx` (`saleId` ASC) VISIBLE,
  CONSTRAINT `fk_employess_acces`
    FOREIGN KEY (`rolId`)
    REFERENCES `ecenario2-bazarDigital`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employess_articles`
    FOREIGN KEY (`articlesId`)
    REFERENCES `ecenario2-bazarDigital`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employess_sales`
    FOREIGN KEY (`saleId`)
    REFERENCES `ecenario2-bazarDigital`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
